spring:
  application:
    name: incentive-service
#  profiles:
#    active: local
  kafka:
    url: localhost:9092
  config:
    import: optional:configserver:${CONFIG_SERVER_ENDPOINT}
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server


server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_ENDPOINT}