server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/deliveries/**, /delivery-service/v3/api-docs
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

springdoc:
  swagger-ui:
    urls[0]:
      name: delivery-service
      url: /delivery-service/v3/api-docs
    use-root-path: true
