spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:18080
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
