spring:
  application:
    name: discovery-server

server:
  port: 19090

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # 다른 Eureka 서버에 이 서버를 등록하지 않음
    fetch-registry: false  # 다른 Eureka 서버의 레지스트리를 가져오지 않음

  server:
    enable-self-preservation: false  # 자기 보호 모드 비활성화
