server:
  port: ${SERVER_PORT}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_URI}
          username: ${CONFIG_SERVER_USERNAME}
          password: ${CONFIG_SERVER_PASSWORD}
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_ENDPOINT}
