server:
  port: 19091
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ohdelivery
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update