CREATE SCHEMA IF NOT EXISTS USER_SCHEMA;
CREATE SCHEMA IF NOT EXISTS MATCH_SCHEMA;
CREATE SCHEMA IF NOT EXISTS DELIVERY_SCHEMA;
CREATE SCHEMA IF NOT EXISTS AUTH_SCHEMA;
CREATE SCHEMA IF NOT EXISTS INCENTIVE_SCHEMA;
CREATE SCHEMA IF NOT EXISTS COUNSEL_SCHEMA;
