spring:
  application:
    name: delivery-service
  config:
    import: optional:configserver:${CONFIG_SERVER_ENDPOINT}
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_ENDPOINT}

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /delivery-service/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
